### ISSUE TITLE
Update SVDB version

### ISSUE THREAD

**Issue by Jakob37** [SMD-Bioinformatics-Lund/nextflow_wgs#118]
SVDB currently runs on version 2.2.0. The latest supported is 2.8.X.

**Comment by alkc** [comment]
I can take this one later on.

## TODO:

- [ ] Split SVDB processes into two. Main one svdb relying on container: https://bioconda.github.io/recipes/svdb/README.html. Postprocessing into separate.
- [ ] Investigate if we can do w/ one main SVDB process.
- [ ] PR and validation
